Controllers/LoginController.cs
using EquipmentManager.Models;
using EquipmentManager.Models.BusinessModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace EquipmentManager.Controllers
{
    public class LoginController : Controller
    {
        private readonly MyDbContext _db;

        public LoginController(MyDbContext db)
        {
            _db = db;
        }

        // GET: LoginController
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Login login)
        {
            if (ModelState.IsValid)
            {
                var f_password = GetMD5(login.Password);
                var data = _db.Accounts.Include(s=>s.Role).Where(s => s.Code.Equals(login.Code) && s.Password.Equals(f_password) && s.Role.Name.Equals("Khách hàng")).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    HttpContext.Session.SetString("UserLogin", data.FirstOrDefault().Name);
                    HttpContext.Session.SetString("UserLogins", data.FirstOrDefault().Code);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("Lỗi", "Tài khoản Email hoặc mật khẩu không đúng");
                }
            }
            return View();
        }
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("UserLogin"); // Hủy session với key UserLogin đã lưu trước đó
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProductController.cs
using EquipmentManager.Models;
using EquipmentManager.Models.BusinessModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using X.PagedList;

namespace EquipmentManager.Controllers
{
    public class ProductController : Controller
    {
        private MyDbContext _db;
        public ProductController(MyDbContext context)
        {
            _db = context;
        }
        // GET: ProductController
        [Route("san-pham",Name = "product")]
        public  async Task<ActionResult> Index(int id,int page =1 )
        {
            var categories = await _db.Categories.ToListAsync();
            ViewBag.category = categories;
            int limit = 12;
            var products = await _db.Products.ToListAsync();
            var product = await _db.Products.OrderBy(x=>x.Id).ToPagedListAsync(page, limit);
            if (id != 0)
            {
                product = await _db.Products.Where(x => x.CategoryId == id).OrderBy(x => x.Id).ToPagedListAsync(page, limit);

            }
            ViewBag.count = products.Count;
            return View(product);
        }

        // GET: ProductController/Details/5
        [Route("chi-tiet-san-pham", Name = "detail")]
        public IActionResult Details(int? id)
        {
            if (id == 0 || _db.Products == null)
            {
                return NotFound();
            }
            var product=  _db.Products.Include(p => p.Category).FirstOrDefault(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            var productDetail = _db.Products.Include(p => p.Category).Where(x => x.CategoryId == product.CategoryId);
           
            if(productDetail != null)
            {
                ViewBag.productCate = productDetail;
            }

            return View("Details", product);
        }







    }
}

Controllers/RegisterController.cs
using EquipmentManager.Models;
using EquipmentManager.Models.BusinessModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace EquipmentManager.Controllers
{
    public class RegisterController : Controller
    {
        private readonly MyDbContext _db;

        public RegisterController(MyDbContext db)
        {
            _db = db;
        }

        // GET: RegisterController
        public ActionResult Index()
        {
            return View();
        }


        // POST: RegisterController/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Account account, string ConfirmPassword)
        {
            if (ModelState.IsValid)
            {
                var check = _db.Accounts.FirstOrDefault(s => s.Code == account.Code);
                if (check == null)
                {
                    if(account.Password != ConfirmPassword)
                    {
                        ViewBag.errorPass = "Mã xác nhận không khớp với mật khẩu đã nhập!";
                    }
                    account.Password = GetMD5(account.Password);
                    account.RoleId = 2;
                    account.Status = true;
                    account.CreatedDate = DateTime.Now;
                    account.ModiredDate = DateTime.Now;
                    _db.Accounts.Add(account);
                    _db.SaveChanges();
                    return RedirectToAction("Index","Login");
                }
                else
                {
                    ViewBag.error = "Tên tài khoản này đã tồn tại!";
                    return View();
                }


            }
            if(ConfirmPassword == null)
            {
                ViewBag.errorPass = "Mã xác nhận không được để trống!!";
            }
            return View();

        }
        //create a string MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }


        // GET: RegisterController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RegisterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegisterController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RegisterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Footer.cshtml
<!--Footer-->
<div class="footer footer-12">
    <div class="footer-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-4 footer-about">
                    <div class="inner mb-4 mb-md-0">
                        <img src="~/images/low-res-logo.png" alt="Optimal" class="mb-3" width="100" height="40" />
                        <div class="custom-text mt-1">
                            <p class="mb-10"><b>Email:</b> haiiyenn210@gmail.com</p>
                            <h2><a href="">0362388823</a></h2>
                            <p>Thứ 2 - Thứ 6: 9 am - 6 pm</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-2 footer-links">
                    <h4 class="h4 body-font text-white"> Thông tin </h4>
                    <ul>
                        <li> <a href="my-account.html"> Tài khoản của Tôi </a> </li>
                        <li> <a href="aboutus-style1.html"> Giới thiệu về chúng tôi </a> </li>
                        <li> <a href="login.html"> Đăng nhập </a> </li>
                        <li> <a href="privacy-policy.html"> Chính sách quyền riêng tư </a> </li>
                        <li> <a href="#"> Điều khoản & amp; điều kiện </a> </li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-2 footer-links">
                    <h4 class="h4 body-font text-white"> Dịch vụ Khách hàng </h4>
                    <ul>
                        <li> <a href="#"> Tài khoản của tôi </a> </li>
                        <li> <a href="#"> Trung tâm Hỗ trợ </a> </li>
                        <li> <a href="#"> Điều khoản & amp; Điều kiện </a> </li>
                        <li> <a href="#"> Trả lại & amp; Trao đổi </a> </li>
                        <li> <a href="#"> Giao hàng & amp; Giao hàng </a> </li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-4 newsletter-col">
                    <div class="display-table pt-md-3 pt-lg-0">
                        <div class="display-table-cell footer-newsletter">
                            <form action="#" method="post">
                                <label class="h4 body-font text-white"> ĐĂNG KÝ BẢN TIN </label>
                                <p> Nhập email của bạn để nhận tin tức hàng ngày và nhận phiếu giảm giá 20% cho tất cả các mặt hàng. </p>
                                <div class="input-group">
                                    <input type="email" class="border-0 rounded-start mb-0 input-group__field newsletter-input" name="EMAIL" value="" placeholder="Email" required>
                                    <span class="input-group__btn"><button type="submit" class="btn btn-primary newsletter__submit rounded-end" name="commit" id="Subscribe"><i class="an an-envelope-l"></i></button></span>
                                </div>
                            </form>
                            <ul class="list-inline social-icons mt-3">
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Facebook"><i class="an an-facebook" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Twitter"><i class="an an-twitter" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Pinterest"><i class="an an-pinterest-p" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Instagram"><i class="an an-instagram" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="TikTok"><i class="an an-tiktok" aria-hidden="true"></i></a></li>
                                <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top" title="Whatsapp"><i class="an an-whatsapp" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom clearfix">
        <div class="container">
            <div class="d-flex-center flex-column justify-content-md-between flex-md-row-reverse">
                <img src="assets/images/payment.png" alt="Paypal Visa Payments" />
            </div>
        </div>
    </div>
</div>
<!--End Footer-->

Views/Shared/_Header.cshtml
@using Newtonsoft.Json
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Filters;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var session = HttpContextAccessor.HttpContext.Session;
    string jsoncart = session.GetString("My-Cart");
    string loginUser = session.GetString("UserLogin");
    int carts = 0;
    var userName = "";
    if (jsoncart != null)
    {
        var cart = JsonConvert.DeserializeObject<List<Cart>>(jsoncart);
        carts = cart.Count();
        foreach (var item in cart)
        {
            userName = item.userName;
        }
    }
   
    

}

<div class="header-main header-12">
    <!--Header-->
    <header class="header header-wrap mih-90 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <!--Logo / Menu Toggle-->
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 align-self-center justify-content-start d-flex">
                    <!--Mobile Toggle-->
                    <button type="button" class="btn--link site-header__menu js-mobile-nav-toggle mobile-nav--open me-3 d-lg-none"><i class="icon an an-times-l"></i><i class="icon an an-bars-l"></i></button>
                    <!--End Mobile Toggle-->
                    <!--Logo-->
                    <div class="logo"><a><img class="logo-img mh-100" src="~/images/low-res-logo.png" alt="Optimal Multipurpose eCommerce Bootstrap 5 Html Template" title="Optimal Multipurpose eCommerce Bootstrap 5 Html Template" width="100" /><span class="logo-txt d-none"></span></a></div>
                    <!--End Logo-->
                </div>
                <!--End Logo / Menu Toggle-->
                <!--Search Inline-->
                <div class="col-1 col-sm-1 col-md-1 col-lg-6 d-none d-lg-block">
                    <form class="form minisearch search-inline" id="header-search1" action="#" method="get">
                        <label class="label d-none"><span>Tìm kiếm</span></label>
                        <div class="control">
                            <div class="searchField d-flex" style="border: 1px solid rgba(255,255,255,.2);">
                                <div class="input-box d-flex w-100">
                                    <input type="text" name="q" placeholder="Tìm kiếm" class="input-text rounded-0 border-start-0 border-end-0" style="color:white">
                                    <button type="submit" title="Search" class="action search"><i class="icon an an-search-l"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--End Search Inline-->
                <!--Right Action-->
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 align-self-center icons-col text-right d-flex justify-content-end">
                    <!--Search-->
                    <div class="site-search iconset d-lg-none"><i class="icon an an-search-l"></i><span class="tooltip-label">Tìm kiếm</span></div>
                    <!--End Search-->
                    <!--Wishlist-->
                    <div class="wishlist-link iconset">
                        <a href="my-wishlist.html"><i class="icon an an-heart-l"></i><span class="wishlist-count counter d-flex-center justify-content-center position-absolute translate-middle rounded-circle">0</span><span class="tooltip-label">Yêu thích</span></a>
                    </div>
                    <!--End Wishlist-->
                    <!--Setting Dropdown-->
                    <div class="user-link iconset">
                        <i class="icon an an-user-expand"></i>@if (loginUser != null)
                        {
                            @Html.Raw("(")
                            @HttpContextAccessor.HttpContext.Session.GetString("UserLogin")
                            @Html.Raw(")")
                        }
                        <span class="tooltip-label">
                            Tài khoản @if (loginUser != null)
                            {
                                @HttpContextAccessor.HttpContext.Session.GetString("UserLogin")
                            }</span></div>
                    <div id="userLinks">
                        <ul class="user-links">
                            <li><a asp-controller="Login" asp-action="Index">Đăng nhập</a></li>
                            <li><a asp-controller="Register" asp-action="Index">Đăng kí</a></li>
                            <li><a href="my-wishlist.html">Yêu thích</a></li>
                            @if (loginUser != null){
                                <li><a asp-controller="Login" asp-action="Logout">Đăng xuất</a></li>
                            }
                           
                        </ul>
                    </div>
                    <!--End Setting Dropdown-->
                    <!--Minicart Drawer-->
                    <div class="header-cart iconset">
                        <a asp-controller="Cart" asp-action="Index" class="site-header__cart btn-minicart">
                            <i class="icon an an-sq-bag"></i><span class="site-cart-count counter d-flex-center justify-content-center position-absolute translate-middle rounded-circle">@if(loginUser == userName){@carts}else{@Html.Raw(0)}</span><span class="tooltip-label">Giỏ hàng</span>
                        </a>
                    </div>
                    <!--End Minicart Drawer-->
                </div>
                <!--End Right Action-->
            </div>
        </div>
        <!--Search Popup-->
        <div id="search-popup" class="search-drawer">
            <div class="container">
                <span class="closeSearch an an-times-l"></span>
                <form class="form minisearch" id="header-search" action="#" method="get">
                    <label class="label"><span>Search</span></label>
                    <div class="control">
                        <div class="searchField" style="border: 1px solid rgba(255,255,255,.2);">
                            <div class="input-box">
                                <button type="submit" title="Tìm kiếm" class="action search"><i class="icon an an-search-l"></i></button>
                                <input type="text" name="q" value="" placeholder="Tìm kiếm" class="input-text">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!--End Search Popup-->
    </header>
    <!--End Header-->
    <!--Main Navigation Desktop-->
    <div class="menu-outer d-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-1 col-sm-1 col-md-1 col-lg-12 align-self-center d-menu-col">
                    <nav class="grid__item" id="AccessibleNav">
                        <ul id="siteNav" class="site-nav medium left hidearrow">
                            <li class="lvl1 parent megamenu">
                                <a asp-controller="Home" asp-action="Index">Trang chủ <i class="an an-angle-down-l"></i></a>

                            </li>
                            <li class="lvl1 parent megamenu">
                                <a asp-controller="Product" asp-action="Index">Sản phẩm <i class="an an-angle-down-l"></i></a>
                            </li>
                            <li class="lvl1 parent dropdown">
                                <a href="#;">Blog <i class="an an-angle-down-l"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!--End Main Navigation Desktop-->
</div>
<!--End Header wrap-->
<!--Mobile Menu-->
<div class="mobile-nav-wrapper" role="navigation">
    <div class="closemobileMenu"><i class="icon an an-times-l pull-right"></i> Đóng</div>
    <ul id="MobileNav" class="mobile-nav">
        <li class="lvl1 parent megamenu">
            <a asp-controller="Home" asp-action="Index">Trang chủ <i class="an an-plus-l"></i></a>

        </li>
        <li class="lvl1 parent megamenu">
            <a asp-controller="Product" asp-action="Index">Sản phẩm <i class="an an-plus-l"></i></a>

        </li>
        <li class="lvl1 parent megamenu">
            <a href="blog-left-sidebar.html">Blog <i class="an an-plus-l"></i></a>
        </li>
        <li class="acLink"></li>
        <li class="lvl1 bottom-link"><a asp-controller="Login" asp-action="Login">Đăng nhập</a></li>
        <li class="lvl1 bottom-link"><a asp-controller="Register" asp-action="Index">Đăng Kí</a></li>
        <li class="lvl1 bottom-link"><a href="my-wishlist.html">Yêu thích</a></li>
        <li class="help bottom-link"><b>SOS?</b><br>Call: 0362388823</li>
    </ul>
</div>
<style>
    .header-12 .menu-outer {
        background-color: #003b6b85;
        padding: 1px 0;
    }

    .header-12.header-main, .header-12 .header-wrap {
        background-color: #11384eed;
        color: #ffffff;
    }

    ::placeholder {
        color: white;
        opacity: 1;
    }

    .header-12 #siteNav > li > a {
        color: white;
        font-size: 15px;
        font-weight: 600;
    }

        .header-12 #siteNav > li > a:hover {
            color: yellow;
        }
</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EquipmentManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="~/assets/css/plugins.css" />
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css" />
    <link rel="stylesheet" href="~/assets/css/responsive.css" />

</head>

<body class="template-index index-demo12 template-product">
    <div class="page-wrapper">
        <!--Header wrap-->
      <partial name="_Header"/>
        <!--End Mobile Menu-->

        <main role="main">
            @RenderBody()
        </main>

        <partial name="_Footer"/>
        <script src="~/assets/js/vendor/jquery-min.js"></script>
        <script src="~/assets/js/vendor/js.cookie.js"></script>
        <!--Including Javascript-->
        <script src="~/assets/js/plugins.js"></script>
        <script src="~/assets/js/main.js"></script>

    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>